/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerAkun;
import java.sql.Connection;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class FormInput extends javax.swing.JFrame {
    
    ControllerAkun cb;
    Connection connection;
    /**
     * Creates new form FormInput
     */
    public FormInput() {
        initComponents();
      
        cb = new ControllerAkun(this);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        pilih_level = new javax.swing.JLabel();
        jl_user = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        easy = new javax.swing.JButton();
        medium = new javax.swing.JButton();
        hard = new javax.swing.JButton();
        Btn_input = new javax.swing.JButton();
        Btn_leaderboard = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(204, 255, 255));
        judul.setText("TTS Kesehatan");
        jPanel1.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(51, 51, 51));
        nama.setText("Name");
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 110, -1, -1));

        pilih_level.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        pilih_level.setForeground(new java.awt.Color(255, 255, 255));
        pilih_level.setText("Level");
        jPanel1.add(pilih_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 234, -1, -1));

        jl_user.setFont(new java.awt.Font("8-bit Operator+ SC", 1, 11)); // NOI18N
        jl_user.setForeground(new java.awt.Color(51, 51, 51));
        jl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        tf_nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 130, 180, 30));

        easy.setBackground(new java.awt.Color(153, 153, 153));
        easy.setForeground(new java.awt.Color(255, 255, 255));
        easy.setText("Easy");
        easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyActionPerformed(evt);
            }
        });
        jPanel1.add(easy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 88, -1));

        medium.setBackground(new java.awt.Color(153, 153, 153));
        medium.setForeground(new java.awt.Color(255, 255, 255));
        medium.setText("Medium");
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });
        jPanel1.add(medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 88, -1));

        hard.setBackground(new java.awt.Color(153, 153, 153));
        hard.setForeground(new java.awt.Color(255, 255, 255));
        hard.setText("Hard");
        hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardActionPerformed(evt);
            }
        });
        jPanel1.add(hard, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 88, -1));

        Btn_input.setBackground(new java.awt.Color(51, 51, 51));
        Btn_input.setForeground(new java.awt.Color(255, 255, 255));
        Btn_input.setText("Input");
        Btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_inputActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 65, -1));

        Btn_leaderboard.setBackground(new java.awt.Color(51, 51, 51));
        Btn_leaderboard.setForeground(new java.awt.Color(255, 255, 255));
        Btn_leaderboard.setText("Leaderboard");
        Btn_leaderboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_leaderboardActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_leaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 150, -1));

        Wallpaper.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\TTSku\\wallpaperflare.com_wallpaper.jpg")); // NOI18N
        jPanel1.add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_inputActionPerformed
        cb.insert();
        cb.Nama();
       
    }//GEN-LAST:event_Btn_inputActionPerformed

    private void hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardActionPerformed
       
    }//GEN-LAST:event_hardActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        
    }//GEN-LAST:event_mediumActionPerformed

    private void easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyActionPerformed
        new Level_Easy().setVisible(true);
        dispose();
    }//GEN-LAST:event_easyActionPerformed

    private void Btn_leaderboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_leaderboardActionPerformed
        // TODO add your handling code here:
         new Leaderboard().setVisible(true);
    }//GEN-LAST:event_Btn_leaderboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_input;
    private javax.swing.JButton Btn_leaderboard;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton easy;
    private javax.swing.JButton hard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_user;
    private javax.swing.JLabel judul;
    private javax.swing.JButton medium;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel pilih_level;
    private javax.swing.JTextField tf_nama;
    // End of variables declaration//GEN-END:variables

    

   

    public JTextField getTf_nama() {
        return tf_nama;
    }

    public void setTf_nama(JTextField tf_nama) {
        this.tf_nama = tf_nama;
    }

    public JLabel getJl_user() {
        return jl_user;
    }

    public void setJl_user(JLabel jl_user) {
        this.jl_user = jl_user;
    }
    
    
    

}
