/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerAkun;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Leaderboard extends javax.swing.JFrame {
    
    ControllerAkun cb;
    Connection connection;
    /**
     * Creates new form Leaderboard
     */
    public Leaderboard() {
        initComponents();
       
        cb = new ControllerAkun(this);
        cb.isiTable();
        
        Tbl_Skor.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        Tbl_Skor.getTableHeader().setOpaque(false);
        Tbl_Skor.getTableHeader().setBackground(new Color(112, 112, 112));
        Tbl_Skor.getTableHeader().setForeground(new Color(255,255,255));
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Leaderboard = new javax.swing.JLabel();
        Btn_Kembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Skor = new javax.swing.JTable();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(320, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Leaderboard.setBackground(new java.awt.Color(51, 102, 255));
        Leaderboard.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        Leaderboard.setForeground(new java.awt.Color(204, 255, 255));
        Leaderboard.setText("LeaderBoard TTS Kesehatan");
        jPanel1.add(Leaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 240, 28));

        Btn_Kembali.setBackground(new java.awt.Color(51, 51, 51));
        Btn_Kembali.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Kembali.setText("Back");
        Btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 80, -1));

        Tbl_Skor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Skor.setFocusable(false);
        Tbl_Skor.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Tbl_Skor.setSelectionBackground(new java.awt.Color(230, 230, 230));
        Tbl_Skor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tbl_Skor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 50, 290, 350));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        jPanel1.add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KembaliActionPerformed
        // TODO add your handling code here:
        new FormInput().setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaderboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Kembali;
    private javax.swing.JLabel Leaderboard;
    private javax.swing.JTable Tbl_Skor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables

    public JTable getTbl_Skor() {
        return Tbl_Skor;
    }

    public void setTbl_Skor(JTable Tbl_Skor) {
        this.Tbl_Skor = Tbl_Skor;
    }

    
    
   
    
    
}
