/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerHard;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Level_Hard extends javax.swing.JFrame {

    ControllerHard ch;
    public Level_Hard() {
        initComponents();
        ch = new ControllerHard(this);
        ch.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hard2_4 = new javax.swing.JTextField();
        hard3_1 = new javax.swing.JTextField();
        hard3_2 = new javax.swing.JTextField();
        hard3_3 = new javax.swing.JTextField();
        hard3_4 = new javax.swing.JTextField();
        hard3_5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        hard3_6 = new javax.swing.JTextField();
        hard3_7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hard3_8 = new javax.swing.JTextField();
        hard5_1 = new javax.swing.JTextField();
        hard4_1 = new javax.swing.JTextField();
        hard4_2 = new javax.swing.JTextField();
        hard1_1 = new javax.swing.JTextField();
        hard4_3 = new javax.swing.JTextField();
        hard1_2 = new javax.swing.JTextField();
        hard4_4 = new javax.swing.JTextField();
        hard1_3 = new javax.swing.JTextField();
        hard5_2 = new javax.swing.JTextField();
        hard1_4 = new javax.swing.JTextField();
        hard5_3 = new javax.swing.JTextField();
        hard1_5 = new javax.swing.JTextField();
        hard1_6 = new javax.swing.JTextField();
        hard1_7 = new javax.swing.JTextField();
        hard2_1 = new javax.swing.JTextField();
        hard2_2 = new javax.swing.JTextField();
        hard2_3 = new javax.swing.JTextField();
        Btn_ulangi = new javax.swing.JButton();
        btn_bantu = new javax.swing.JButton();
        btn_kumpul = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hard = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        hard2_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard2_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard2_4ActionPerformed(evt);
            }
        });
        hard2_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard2_4KeyTyped(evt);
            }
        });

        hard3_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard3_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard3_1ActionPerformed(evt);
            }
        });
        hard3_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard3_1KeyTyped(evt);
            }
        });

        hard3_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard3_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard3_2ActionPerformed(evt);
            }
        });
        hard3_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard3_2KeyTyped(evt);
            }
        });

        hard3_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard3_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard3_3ActionPerformed(evt);
            }
        });
        hard3_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard3_3KeyTyped(evt);
            }
        });

        hard3_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard3_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard3_4ActionPerformed(evt);
            }
        });
        hard3_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard3_4KeyTyped(evt);
            }
        });

        hard3_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard3_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard3_5ActionPerformed(evt);
            }
        });
        hard3_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard3_5KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("TTS Kesehatan");

        hard3_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard3_6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard3_6ActionPerformed(evt);
            }
        });
        hard3_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard3_6KeyTyped(evt);
            }
        });

        hard3_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard3_7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard3_7ActionPerformed(evt);
            }
        });
        hard3_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard3_7KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 255));
        jLabel2.setText("Level Hard");

        hard3_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard3_8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard3_8ActionPerformed(evt);
            }
        });
        hard3_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard3_8KeyTyped(evt);
            }
        });

        hard5_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard5_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard5_1ActionPerformed(evt);
            }
        });
        hard5_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard5_1KeyTyped(evt);
            }
        });

        hard4_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard4_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard4_1ActionPerformed(evt);
            }
        });
        hard4_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard4_1KeyTyped(evt);
            }
        });

        hard4_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard4_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard4_2ActionPerformed(evt);
            }
        });
        hard4_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard4_2KeyTyped(evt);
            }
        });

        hard1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard1_1ActionPerformed(evt);
            }
        });
        hard1_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard1_1KeyTyped(evt);
            }
        });

        hard4_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard4_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard4_3ActionPerformed(evt);
            }
        });
        hard4_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard4_3KeyTyped(evt);
            }
        });

        hard1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard1_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard1_2ActionPerformed(evt);
            }
        });
        hard1_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard1_2KeyTyped(evt);
            }
        });

        hard4_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard4_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard4_4ActionPerformed(evt);
            }
        });
        hard4_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard4_4KeyTyped(evt);
            }
        });

        hard1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard1_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard1_3ActionPerformed(evt);
            }
        });
        hard1_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard1_3KeyTyped(evt);
            }
        });

        hard5_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard5_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard5_2ActionPerformed(evt);
            }
        });
        hard5_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard5_2KeyTyped(evt);
            }
        });

        hard1_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard1_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard1_4ActionPerformed(evt);
            }
        });
        hard1_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard1_4KeyTyped(evt);
            }
        });

        hard5_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard5_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard5_3ActionPerformed(evt);
            }
        });
        hard5_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard5_3KeyTyped(evt);
            }
        });

        hard1_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard1_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard1_5ActionPerformed(evt);
            }
        });
        hard1_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard1_5KeyTyped(evt);
            }
        });

        hard1_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard1_6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard1_6ActionPerformed(evt);
            }
        });
        hard1_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard1_6KeyTyped(evt);
            }
        });

        hard1_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard1_7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard1_7ActionPerformed(evt);
            }
        });
        hard1_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard1_7KeyTyped(evt);
            }
        });

        hard2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard2_1ActionPerformed(evt);
            }
        });
        hard2_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard2_1KeyTyped(evt);
            }
        });

        hard2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard2_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard2_2ActionPerformed(evt);
            }
        });
        hard2_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard2_2KeyTyped(evt);
            }
        });

        hard2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hard2_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hard2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hard2_3ActionPerformed(evt);
            }
        });
        hard2_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hard2_3KeyTyped(evt);
            }
        });

        Btn_ulangi.setBackground(new java.awt.Color(102, 102, 102));
        Btn_ulangi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Btn_ulangi.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ulangi.setText("Retry");
        Btn_ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ulangiActionPerformed(evt);
            }
        });

        btn_bantu.setBackground(new java.awt.Color(102, 102, 102));
        btn_bantu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_bantu.setForeground(new java.awt.Color(255, 255, 255));
        btn_bantu.setText("Assist ");
        btn_bantu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bantuMouseClicked(evt);
            }
        });
        btn_bantu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bantuActionPerformed(evt);
            }
        });

        btn_kumpul.setBackground(new java.awt.Color(102, 102, 102));
        btn_kumpul.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_kumpul.setForeground(new java.awt.Color(255, 255, 255));
        btn_kumpul.setText("Submit");
        btn_kumpul.setMaximumSize(new java.awt.Dimension(73, 21));
        btn_kumpul.setMinimumSize(new java.awt.Dimension(73, 21));
        btn_kumpul.setPreferredSize(new java.awt.Dimension(73, 21));
        btn_kumpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kumpulActionPerformed(evt);
            }
        });

        tbl_hard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_hard);

        jLabel4.setText("2");

        jLabel5.setText("3");

        jLabel6.setText("4");

        jLabel7.setText("5");

        btn_kembali.setText("Back");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        jLabel8.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(982, 982, 982))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_kembali)
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hard2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hard2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hard4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(235, 235, 235)
                                                .addComponent(hard4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(hard4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hard4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(hard3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(hard3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hard3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Btn_ulangi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btn_bantu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btn_kumpul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hard3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hard3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hard3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(hard3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hard3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hard5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(hard5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hard5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(hard2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184)))))
                .addGap(526, 526, 526))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btn_kembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn_ulangi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_bantu)
                        .addGap(9, 9, 9)
                        .addComponent(btn_kumpul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hard1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(hard2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hard2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hard2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hard4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hard4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hard3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hard5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hard4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hard4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hard5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hard5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hard2_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard2_3KeyTyped
if(hard2_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard2_3KeyTyped

    private void hard2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard2_3ActionPerformed

    private void hard2_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard2_2KeyTyped
if(hard2_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard2_2KeyTyped

    private void hard2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard2_2ActionPerformed

    private void hard2_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard2_1KeyTyped
if(hard2_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard2_1KeyTyped

    private void hard2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard2_1ActionPerformed

    private void hard1_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard1_7KeyTyped
if(hard1_7.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard1_7KeyTyped

    private void hard1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard1_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard1_7ActionPerformed

    private void hard1_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard1_6KeyTyped
if(hard1_6.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard1_6KeyTyped

    private void hard1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard1_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard1_6ActionPerformed

    private void hard1_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard1_5KeyTyped
if(hard1_5.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard1_5KeyTyped

    private void hard1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard1_5ActionPerformed

    private void hard5_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard5_3KeyTyped
        if(hard5_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard5_3KeyTyped

    private void hard5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard5_3ActionPerformed

    private void hard1_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard1_4KeyTyped
    if(hard1_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard1_4KeyTyped

    private void hard1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard1_4ActionPerformed

    private void hard5_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard5_2KeyTyped
        if(hard5_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard5_2KeyTyped

    private void hard5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard5_2ActionPerformed

    private void hard1_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard1_3KeyTyped
       if(hard1_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard1_3KeyTyped

    private void hard1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard1_3ActionPerformed

    private void hard4_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard4_4KeyTyped
        if(hard4_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard4_4KeyTyped

    private void hard4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard4_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard4_4ActionPerformed

    private void hard1_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard1_2KeyTyped
if(hard1_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard1_2KeyTyped

    private void hard1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard1_2ActionPerformed

    private void hard4_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard4_3KeyTyped
        if(hard4_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard4_3KeyTyped

    private void hard4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard4_3ActionPerformed

    private void hard1_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard1_1KeyTyped
        if(hard1_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard1_1KeyTyped

    private void hard1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard1_1ActionPerformed

    private void hard4_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard4_2KeyTyped
        if(hard4_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard4_2KeyTyped

    private void hard4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard4_2ActionPerformed

    private void hard4_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard4_1KeyTyped
if(hard4_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard4_1KeyTyped

    private void hard4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard4_1ActionPerformed

    private void hard5_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard5_1KeyTyped
if(hard5_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard5_1KeyTyped

    private void hard5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard5_1ActionPerformed

    private void hard3_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard3_8KeyTyped
if(hard3_8.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard3_8KeyTyped

    private void hard3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard3_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard3_8ActionPerformed

    private void hard3_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard3_7KeyTyped
if(hard3_7.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard3_7KeyTyped

    private void hard3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard3_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard3_7ActionPerformed

    private void hard3_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard3_6KeyTyped
if(hard3_6.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard3_6KeyTyped

    private void hard3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard3_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard3_6ActionPerformed

    private void hard3_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard3_5KeyTyped
if(hard3_5.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard3_5KeyTyped

    private void hard3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard3_5ActionPerformed

    private void hard3_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard3_4KeyTyped
if(hard3_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard3_4KeyTyped

    private void hard3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard3_4ActionPerformed

    private void hard3_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard3_3KeyTyped
if(hard3_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard3_3KeyTyped

    private void hard3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard3_3ActionPerformed

    private void hard3_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard3_2KeyTyped
if(hard3_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard3_2KeyTyped

    private void hard3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard3_2ActionPerformed

    private void hard3_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard3_1KeyTyped
if(hard3_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard3_1KeyTyped

    private void hard3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard3_1ActionPerformed

    private void hard2_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hard2_4KeyTyped
if(hard2_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_hard2_4KeyTyped

    private void hard2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hard2_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hard2_4ActionPerformed

    private void Btn_ulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ulangiActionPerformed
        ch.reset();

    }//GEN-LAST:event_Btn_ulangiActionPerformed

    private void btn_bantuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bantuMouseClicked
        ch.Bantuan(tbl_hard.getSelectedRow());
    }//GEN-LAST:event_btn_bantuMouseClicked

    private void btn_bantuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bantuActionPerformed

    }//GEN-LAST:event_btn_bantuActionPerformed

    private void btn_kumpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kumpulActionPerformed
        ch.check_jawab();
    }//GEN-LAST:event_btn_kumpulActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        new FormInput().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    public JButton getBtn_ulangi() {
        return Btn_ulangi;
    }

    public void setBtn_ulangi(JButton Btn_ulangi) {
        this.Btn_ulangi = Btn_ulangi;
    }

    public JButton getBtn_bantu() {
        return btn_bantu;
    }

    public void setBtn_bantu(JButton btn_bantu) {
        this.btn_bantu = btn_bantu;
    }

    public JButton getBtn_kembali() {
        return btn_kembali;
    }

    public void setBtn_kembali(JButton btn_kembali) {
        this.btn_kembali = btn_kembali;
    }

    public JButton getBtn_kumpul() {
        return btn_kumpul;
    }

    public void setBtn_kumpul(JButton btn_kumpul) {
        this.btn_kumpul = btn_kumpul;
    }

    public JTextField getHard1_1() {
        return hard1_1;
    }

    public void setHard1_1(JTextField hard1_1) {
        this.hard1_1 = hard1_1;
    }

    public JTextField getHard1_2() {
        return hard1_2;
    }

    public void setHard1_2(JTextField hard1_2) {
        this.hard1_2 = hard1_2;
    }

    public JTextField getHard1_3() {
        return hard1_3;
    }

    public void setHard1_3(JTextField hard1_3) {
        this.hard1_3 = hard1_3;
    }

    public JTextField getHard1_4() {
        return hard1_4;
    }

    public void setHard1_4(JTextField hard1_4) {
        this.hard1_4 = hard1_4;
    }

    public JTextField getHard1_5() {
        return hard1_5;
    }

    public void setHard1_5(JTextField hard1_5) {
        this.hard1_5 = hard1_5;
    }

    public JTextField getHard1_6() {
        return hard1_6;
    }

    public void setHard1_6(JTextField hard1_6) {
        this.hard1_6 = hard1_6;
    }

    public JTextField getHard1_7() {
        return hard1_7;
    }

    public void setHard1_7(JTextField hard1_7) {
        this.hard1_7 = hard1_7;
    }

    public JTextField getHard2_1() {
        return hard2_1;
    }

    public void setHard2_1(JTextField hard2_1) {
        this.hard2_1 = hard2_1;
    }

    public JTextField getHard2_2() {
        return hard2_2;
    }

    public void setHard2_2(JTextField hard2_2) {
        this.hard2_2 = hard2_2;
    }

    public JTextField getHard2_3() {
        return hard2_3;
    }

    public void setHard2_3(JTextField hard2_3) {
        this.hard2_3 = hard2_3;
    }

    public JTextField getHard2_4() {
        return hard2_4;
    }

    public void setHard2_4(JTextField hard2_4) {
        this.hard2_4 = hard2_4;
    }

    public JTextField getHard3_1() {
        return hard3_1;
    }

    public void setHard3_1(JTextField hard3_1) {
        this.hard3_1 = hard3_1;
    }

    public JTextField getHard3_2() {
        return hard3_2;
    }

    public void setHard3_2(JTextField hard3_2) {
        this.hard3_2 = hard3_2;
    }

    public JTextField getHard3_3() {
        return hard3_3;
    }

    public void setHard3_3(JTextField hard3_3) {
        this.hard3_3 = hard3_3;
    }

    public JTextField getHard3_4() {
        return hard3_4;
    }

    public void setHard3_4(JTextField hard3_4) {
        this.hard3_4 = hard3_4;
    }

    public JTextField getHard3_5() {
        return hard3_5;
    }

    public void setHard3_5(JTextField hard3_5) {
        this.hard3_5 = hard3_5;
    }

    public JTextField getHard3_6() {
        return hard3_6;
    }

    public void setHard3_6(JTextField hard3_6) {
        this.hard3_6 = hard3_6;
    }

    public JTextField getHard3_7() {
        return hard3_7;
    }

    public void setHard3_7(JTextField hard3_7) {
        this.hard3_7 = hard3_7;
    }

    public JTextField getHard3_8() {
        return hard3_8;
    }

    public void setHard3_8(JTextField hard3_8) {
        this.hard3_8 = hard3_8;
    }

    public JTextField getHard4_1() {
        return hard4_1;
    }

    public void setHard4_1(JTextField hard4_1) {
        this.hard4_1 = hard4_1;
    }

    public JTextField getHard4_2() {
        return hard4_2;
    }

    public void setHard4_2(JTextField hard4_2) {
        this.hard4_2 = hard4_2;
    }

    public JTextField getHard4_3() {
        return hard4_3;
    }

    public void setHard4_3(JTextField hard4_3) {
        this.hard4_3 = hard4_3;
    }

    public JTextField getHard4_4() {
        return hard4_4;
    }

    public void setHard4_4(JTextField hard4_4) {
        this.hard4_4 = hard4_4;
    }

    public JTextField getHard5_1() {
        return hard5_1;
    }

    public void setHard5_1(JTextField hard5_1) {
        this.hard5_1 = hard5_1;
    }

    public JTextField getHard5_2() {
        return hard5_2;
    }

    public void setHard5_2(JTextField hard5_2) {
        this.hard5_2 = hard5_2;
    }

    public JTextField getHard5_3() {
        return hard5_3;
    }

    public void setHard5_3(JTextField hard5_3) {
        this.hard5_3 = hard5_3;
    }

    public JTable getTbl_hard() {
        return tbl_hard;
    }

    public void setTbl_hard(JTable tbl_hard) {
        this.tbl_hard = tbl_hard;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level_Hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level_Hard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ulangi;
    private javax.swing.JButton btn_bantu;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_kumpul;
    private javax.swing.JTextField hard1_1;
    private javax.swing.JTextField hard1_2;
    private javax.swing.JTextField hard1_3;
    private javax.swing.JTextField hard1_4;
    private javax.swing.JTextField hard1_5;
    private javax.swing.JTextField hard1_6;
    private javax.swing.JTextField hard1_7;
    private javax.swing.JTextField hard2_1;
    private javax.swing.JTextField hard2_2;
    private javax.swing.JTextField hard2_3;
    private javax.swing.JTextField hard2_4;
    private javax.swing.JTextField hard3_1;
    private javax.swing.JTextField hard3_2;
    private javax.swing.JTextField hard3_3;
    private javax.swing.JTextField hard3_4;
    private javax.swing.JTextField hard3_5;
    private javax.swing.JTextField hard3_6;
    private javax.swing.JTextField hard3_7;
    private javax.swing.JTextField hard3_8;
    private javax.swing.JTextField hard4_1;
    private javax.swing.JTextField hard4_2;
    private javax.swing.JTextField hard4_3;
    private javax.swing.JTextField hard4_4;
    private javax.swing.JTextField hard5_1;
    private javax.swing.JTextField hard5_2;
    private javax.swing.JTextField hard5_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_hard;
    // End of variables declaration//GEN-END:variables
}
