/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerMed;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Level_Medium extends javax.swing.JFrame {

    ControllerMed cm;
    public Level_Medium() {
        initComponents();
        cm = new ControllerMed(this);
        cm.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        med4_3 = new javax.swing.JTextField();
        med6_1 = new javax.swing.JTextField();
        med1_1 = new javax.swing.JTextField();
        med6_2 = new javax.swing.JTextField();
        med1_2 = new javax.swing.JTextField();
        med5_1 = new javax.swing.JTextField();
        med1_3 = new javax.swing.JTextField();
        med5_2 = new javax.swing.JTextField();
        med1_4 = new javax.swing.JTextField();
        med5_3 = new javax.swing.JTextField();
        med1_5 = new javax.swing.JTextField();
        med5_4 = new javax.swing.JTextField();
        med1_6 = new javax.swing.JTextField();
        med4_4 = new javax.swing.JTextField();
        med1_7 = new javax.swing.JTextField();
        med6_3 = new javax.swing.JTextField();
        med1_8 = new javax.swing.JTextField();
        med6_4 = new javax.swing.JTextField();
        med1_9 = new javax.swing.JTextField();
        med1_10 = new javax.swing.JTextField();
        med6_5 = new javax.swing.JTextField();
        med7_1 = new javax.swing.JTextField();
        med2_2 = new javax.swing.JTextField();
        med7_2 = new javax.swing.JTextField();
        med2_3 = new javax.swing.JTextField();
        med7_3 = new javax.swing.JTextField();
        med3_1 = new javax.swing.JTextField();
        med7_4 = new javax.swing.JTextField();
        med2_1 = new javax.swing.JTextField();
        med7_5 = new javax.swing.JTextField();
        med3_2 = new javax.swing.JTextField();
        med7_6 = new javax.swing.JTextField();
        med3_3 = new javax.swing.JTextField();
        soal = new javax.swing.JLabel();
        med3_4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        med3_5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        med4_1 = new javax.swing.JTextField();
        med4_2 = new javax.swing.JTextField();
        btn_kembali = new javax.swing.JButton();
        Btn_ulangi = new javax.swing.JButton();
        btn_bantu = new javax.swing.JButton();
        btn_kumpul = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_medium = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        med4_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med4_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med4_3ActionPerformed(evt);
            }
        });
        med4_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med4_3KeyTyped(evt);
            }
        });

        med6_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med6_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med6_1ActionPerformed(evt);
            }
        });
        med6_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med6_1KeyTyped(evt);
            }
        });

        med1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_1ActionPerformed(evt);
            }
        });
        med1_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_1KeyTyped(evt);
            }
        });

        med6_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med6_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med6_2ActionPerformed(evt);
            }
        });
        med6_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med6_2KeyTyped(evt);
            }
        });

        med1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_2ActionPerformed(evt);
            }
        });
        med1_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_2KeyTyped(evt);
            }
        });

        med5_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med5_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med5_1ActionPerformed(evt);
            }
        });
        med5_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med5_1KeyTyped(evt);
            }
        });

        med1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_3ActionPerformed(evt);
            }
        });
        med1_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_3KeyTyped(evt);
            }
        });

        med5_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med5_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med5_2ActionPerformed(evt);
            }
        });
        med5_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med5_2KeyTyped(evt);
            }
        });

        med1_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_4ActionPerformed(evt);
            }
        });
        med1_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_4KeyTyped(evt);
            }
        });

        med5_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med5_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med5_3ActionPerformed(evt);
            }
        });
        med5_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med5_3KeyTyped(evt);
            }
        });

        med1_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_5ActionPerformed(evt);
            }
        });
        med1_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_5KeyTyped(evt);
            }
        });

        med5_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med5_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med5_4ActionPerformed(evt);
            }
        });
        med5_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med5_4KeyTyped(evt);
            }
        });

        med1_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_6ActionPerformed(evt);
            }
        });
        med1_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_6KeyTyped(evt);
            }
        });

        med4_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med4_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med4_4ActionPerformed(evt);
            }
        });
        med4_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med4_4KeyTyped(evt);
            }
        });

        med1_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_7ActionPerformed(evt);
            }
        });
        med1_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_7KeyTyped(evt);
            }
        });

        med6_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med6_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med6_3ActionPerformed(evt);
            }
        });
        med6_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med6_3KeyTyped(evt);
            }
        });

        med1_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_8ActionPerformed(evt);
            }
        });
        med1_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_8KeyTyped(evt);
            }
        });

        med6_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med6_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med6_4ActionPerformed(evt);
            }
        });
        med6_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med6_4KeyTyped(evt);
            }
        });

        med1_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_9ActionPerformed(evt);
            }
        });
        med1_9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_9KeyTyped(evt);
            }
        });

        med1_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med1_10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med1_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1_10ActionPerformed(evt);
            }
        });
        med1_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med1_10KeyTyped(evt);
            }
        });

        med6_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med6_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med6_5ActionPerformed(evt);
            }
        });
        med6_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med6_5KeyTyped(evt);
            }
        });

        med7_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med7_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med7_1ActionPerformed(evt);
            }
        });
        med7_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med7_1KeyTyped(evt);
            }
        });

        med2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med2_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med2_2ActionPerformed(evt);
            }
        });
        med2_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med2_2KeyTyped(evt);
            }
        });

        med7_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med7_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med7_2ActionPerformed(evt);
            }
        });
        med7_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med7_2KeyTyped(evt);
            }
        });

        med2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med2_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med2_3ActionPerformed(evt);
            }
        });
        med2_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med2_3KeyTyped(evt);
            }
        });

        med7_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med7_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med7_3ActionPerformed(evt);
            }
        });
        med7_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med7_3KeyTyped(evt);
            }
        });

        med3_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med3_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med3_1ActionPerformed(evt);
            }
        });
        med3_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med3_1KeyTyped(evt);
            }
        });

        med7_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med7_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med7_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med7_4ActionPerformed(evt);
            }
        });
        med7_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med7_4KeyTyped(evt);
            }
        });

        med2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med2_1ActionPerformed(evt);
            }
        });
        med2_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med2_1KeyTyped(evt);
            }
        });

        med7_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med7_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med7_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med7_5ActionPerformed(evt);
            }
        });
        med7_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med7_5KeyTyped(evt);
            }
        });

        med3_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med3_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med3_2ActionPerformed(evt);
            }
        });
        med3_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med3_2KeyTyped(evt);
            }
        });

        med7_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med7_6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med7_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med7_6ActionPerformed(evt);
            }
        });
        med7_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med7_6KeyTyped(evt);
            }
        });

        med3_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med3_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med3_3ActionPerformed(evt);
            }
        });
        med3_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med3_3KeyTyped(evt);
            }
        });

        soal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soalMouseClicked(evt);
            }
        });

        med3_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med3_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med3_4ActionPerformed(evt);
            }
        });
        med3_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med3_4KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("TTS Kesehatan");

        med3_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med3_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med3_5ActionPerformed(evt);
            }
        });
        med3_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med3_5KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Level Medium");

        med4_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med4_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med4_1ActionPerformed(evt);
            }
        });
        med4_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med4_1KeyTyped(evt);
            }
        });

        med4_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        med4_2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        med4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med4_2ActionPerformed(evt);
            }
        });
        med4_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med4_2KeyTyped(evt);
            }
        });

        btn_kembali.setText("Back");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        Btn_ulangi.setBackground(new java.awt.Color(102, 102, 102));
        Btn_ulangi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Btn_ulangi.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ulangi.setText("Retry");
        Btn_ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ulangiActionPerformed(evt);
            }
        });

        btn_bantu.setBackground(new java.awt.Color(102, 102, 102));
        btn_bantu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_bantu.setForeground(new java.awt.Color(255, 255, 255));
        btn_bantu.setText("Assist ");
        btn_bantu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bantuMouseClicked(evt);
            }
        });
        btn_bantu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bantuActionPerformed(evt);
            }
        });

        btn_kumpul.setBackground(new java.awt.Color(102, 102, 102));
        btn_kumpul.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_kumpul.setForeground(new java.awt.Color(255, 255, 255));
        btn_kumpul.setText("Submit");
        btn_kumpul.setMaximumSize(new java.awt.Dimension(73, 21));
        btn_kumpul.setMinimumSize(new java.awt.Dimension(73, 21));
        btn_kumpul.setPreferredSize(new java.awt.Dimension(73, 21));
        btn_kumpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kumpulActionPerformed(evt);
            }
        });

        tbl_medium.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_medium);

        jLabel3.setText("1");

        jLabel4.setText("2");

        jLabel5.setText("3");

        jLabel6.setText("5");

        jLabel7.setText("4");

        jLabel8.setText("6");

        jLabel9.setText("7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(soal, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                                .addGap(17, 17, 17)))
                                        .addGap(253, 253, 253))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_ulangi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_bantu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_kumpul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(med3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(med3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(med3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(med3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(med3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(med2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(med1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(med1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(med2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(57, 57, 57)
                                                        .addComponent(med2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(med1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(med1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med1_10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(med4_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(med4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(med4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(med6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(med6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(med6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(med6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(med6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(med7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(med7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(med7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(med7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(med7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(med5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(med5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(med5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 55, Short.MAX_VALUE)))))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_kembali))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(med2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Btn_ulangi)
                                    .addGap(9, 9, 9)
                                    .addComponent(btn_bantu)
                                    .addGap(9, 9, 9)
                                    .addComponent(btn_kumpul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(med1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med1_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(med4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(med2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(med4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(med4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(med2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(med3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(med6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(med6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(med6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(med6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(med6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtn_ulangi() {
        return Btn_ulangi;
    }

    public void setBtn_ulangi(JButton Btn_ulangi) {
        this.Btn_ulangi = Btn_ulangi;
    }

    public JButton getBtn_bantu() {
        return btn_bantu;
    }

    public void setBtn_bantu(JButton btn_bantu) {
        this.btn_bantu = btn_bantu;
    }

    public JButton getBtn_kembali() {
        return btn_kembali;
    }

    public void setBtn_kembali(JButton btn_kembali) {
        this.btn_kembali = btn_kembali;
    }

    public JButton getBtn_kumpul() {
        return btn_kumpul;
    }

    public void setBtn_kumpul(JButton btn_kumpul) {
        this.btn_kumpul = btn_kumpul;
    }

    public JTextField getMed1_1() {
        return med1_1;
    }

    public void setMed1_1(JTextField med1_1) {
        this.med1_1 = med1_1;
    }

    public JTextField getMed1_10() {
        return med1_10;
    }

    public void setMed1_10(JTextField med1_10) {
        this.med1_10 = med1_10;
    }

    public JTextField getMed1_2() {
        return med1_2;
    }

    public void setMed1_2(JTextField med1_2) {
        this.med1_2 = med1_2;
    }

    public JTextField getMed1_3() {
        return med1_3;
    }

    public void setMed1_3(JTextField med1_3) {
        this.med1_3 = med1_3;
    }

    public JTextField getMed1_4() {
        return med1_4;
    }

    public void setMed1_4(JTextField med1_4) {
        this.med1_4 = med1_4;
    }

    public JTextField getMed1_5() {
        return med1_5;
    }

    public void setMed1_5(JTextField med1_5) {
        this.med1_5 = med1_5;
    }

    public JTextField getMed1_6() {
        return med1_6;
    }

    public void setMed1_6(JTextField med1_6) {
        this.med1_6 = med1_6;
    }

    public JTextField getMed1_7() {
        return med1_7;
    }

    public void setMed1_7(JTextField med1_7) {
        this.med1_7 = med1_7;
    }

    public JTextField getMed1_8() {
        return med1_8;
    }

    public void setMed1_8(JTextField med1_8) {
        this.med1_8 = med1_8;
    }

    public JTextField getMed1_9() {
        return med1_9;
    }

    public void setMed1_9(JTextField med1_9) {
        this.med1_9 = med1_9;
    }

    public JTextField getMed2_1() {
        return med2_1;
    }

    public void setMed2_1(JTextField med2_1) {
        this.med2_1 = med2_1;
    }

    public JTextField getMed2_2() {
        return med2_2;
    }

    public void setMed2_2(JTextField med2_2) {
        this.med2_2 = med2_2;
    }

    public JTextField getMed2_3() {
        return med2_3;
    }

    public void setMed2_3(JTextField med2_3) {
        this.med2_3 = med2_3;
    }

    public JTextField getMed3_1() {
        return med3_1;
    }

    public void setMed3_1(JTextField med3_1) {
        this.med3_1 = med3_1;
    }

    public JTextField getMed3_2() {
        return med3_2;
    }

    public void setMed3_2(JTextField med3_2) {
        this.med3_2 = med3_2;
    }

    public JTextField getMed3_3() {
        return med3_3;
    }

    public void setMed3_3(JTextField med3_3) {
        this.med3_3 = med3_3;
    }

    public JTextField getMed3_4() {
        return med3_4;
    }

    public void setMed3_4(JTextField med3_4) {
        this.med3_4 = med3_4;
    }

    public JTextField getMed3_5() {
        return med3_5;
    }

    public void setMed3_5(JTextField med3_5) {
        this.med3_5 = med3_5;
    }

    public JTextField getMed4_1() {
        return med4_1;
    }

    public void setMed4_1(JTextField med4_1) {
        this.med4_1 = med4_1;
    }

    public JTextField getMed4_2() {
        return med4_2;
    }

    public void setMed4_2(JTextField med4_2) {
        this.med4_2 = med4_2;
    }

    public JTextField getMed4_3() {
        return med4_3;
    }

    public void setMed4_3(JTextField med4_3) {
        this.med4_3 = med4_3;
    }

    public JTextField getMed4_4() {
        return med4_4;
    }

    public void setMed4_4(JTextField med4_4) {
        this.med4_4 = med4_4;
    }

    public JTextField getMed5_1() {
        return med5_1;
    }

    public void setMed5_1(JTextField med5_1) {
        this.med5_1 = med5_1;
    }

    public JTextField getMed5_2() {
        return med5_2;
    }

    public void setMed5_2(JTextField med5_2) {
        this.med5_2 = med5_2;
    }

    public JTextField getMed5_3() {
        return med5_3;
    }

    public void setMed5_3(JTextField med5_3) {
        this.med5_3 = med5_3;
    }

    public JTextField getMed5_4() {
        return med5_4;
    }

    public void setMed5_4(JTextField med5_4) {
        this.med5_4 = med5_4;
    }

    public JTextField getMed6_1() {
        return med6_1;
    }

    public void setMed6_1(JTextField med6_1) {
        this.med6_1 = med6_1;
    }

    public JTextField getMed6_2() {
        return med6_2;
    }

    public void setMed6_2(JTextField med6_2) {
        this.med6_2 = med6_2;
    }

    public JTextField getMed6_3() {
        return med6_3;
    }

    public void setMed6_3(JTextField med6_3) {
        this.med6_3 = med6_3;
    }

    public JTextField getMed6_4() {
        return med6_4;
    }

    public void setMed6_4(JTextField med6_4) {
        this.med6_4 = med6_4;
    }

    public JTextField getMed6_5() {
        return med6_5;
    }

    public void setMed6_5(JTextField med6_5) {
        this.med6_5 = med6_5;
    }

    public JTextField getMed7_1() {
        return med7_1;
    }

    public void setMed7_1(JTextField med7_1) {
        this.med7_1 = med7_1;
    }

    public JTextField getMed7_2() {
        return med7_2;
    }

    public void setMed7_2(JTextField med7_2) {
        this.med7_2 = med7_2;
    }

    public JTextField getMed7_3() {
        return med7_3;
    }

    public void setMed7_3(JTextField med7_3) {
        this.med7_3 = med7_3;
    }

    public JTextField getMed7_4() {
        return med7_4;
    }

    public void setMed7_4(JTextField med7_4) {
        this.med7_4 = med7_4;
    }

    public JTextField getMed7_5() {
        return med7_5;
    }

    public void setMed7_5(JTextField med7_5) {
        this.med7_5 = med7_5;
    }

    public JTextField getMed7_6() {
        return med7_6;
    }

    public void setMed7_6(JTextField med7_6) {
        this.med7_6 = med7_6;
    }

    public JTable getTbl_medium() {
        return tbl_medium;
    }

    public void setTbl_medium(JTable tbl_medium) {
        this.tbl_medium = tbl_medium;
    }

    private void med4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med4_3ActionPerformed

    private void med4_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med4_3KeyTyped
        if(med4_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med4_3KeyTyped

    private void med6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med6_1ActionPerformed

    private void med6_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med6_1KeyTyped
        if(med6_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med6_1KeyTyped

    private void med1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_1ActionPerformed

    private void med1_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_1KeyTyped
if(med1_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_1KeyTyped

    private void med6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med6_2ActionPerformed

    private void med6_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med6_2KeyTyped
        if(med6_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med6_2KeyTyped

    private void med1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_2ActionPerformed

    private void med1_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_2KeyTyped
if(med1_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_2KeyTyped

    private void med5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med5_1ActionPerformed

    private void med5_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med5_1KeyTyped
       if(med5_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med5_1KeyTyped

    private void med1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_3ActionPerformed

    private void med1_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_3KeyTyped
if(med1_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_3KeyTyped

    private void med5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med5_2ActionPerformed

    private void med5_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med5_2KeyTyped
        if(med5_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med5_2KeyTyped

    private void med1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_4ActionPerformed

    private void med1_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_4KeyTyped
       if(med1_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_4KeyTyped

    private void med5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med5_3ActionPerformed

    private void med5_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med5_3KeyTyped
        if(med5_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med5_3KeyTyped

    private void med1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_5ActionPerformed

    private void med1_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_5KeyTyped
if(med1_5.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_5KeyTyped

    private void med5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med5_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med5_4ActionPerformed

    private void med5_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med5_4KeyTyped
        if(med5_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med5_4KeyTyped

    private void med1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_6ActionPerformed

    private void med1_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_6KeyTyped
if(med1_6.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_6KeyTyped

    private void med4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med4_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med4_4ActionPerformed

    private void med4_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med4_4KeyTyped
        if(med4_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med4_4KeyTyped

    private void med1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_7ActionPerformed

    private void med1_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_7KeyTyped
if(med1_7.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_7KeyTyped

    private void med6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med6_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med6_3ActionPerformed

    private void med6_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med6_3KeyTyped
       if(med6_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med6_3KeyTyped

    private void med1_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_8ActionPerformed

    private void med1_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_8KeyTyped
        if(med1_8.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_8KeyTyped

    private void med6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med6_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med6_4ActionPerformed

    private void med6_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med6_4KeyTyped
        if(med6_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med6_4KeyTyped

    private void med1_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_9ActionPerformed

    private void med1_9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_9KeyTyped
        if(med1_9.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_9KeyTyped

    private void med1_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med1_10ActionPerformed

    private void med1_10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1_10KeyTyped
        if(med1_10.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med1_10KeyTyped

    private void med6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med6_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med6_5ActionPerformed

    private void med6_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med6_5KeyTyped
        if(med6_5.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med6_5KeyTyped

    private void med7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med7_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med7_1ActionPerformed

    private void med7_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med7_1KeyTyped
        if(med7_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med7_1KeyTyped

    private void med2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med2_2ActionPerformed

    private void med2_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med2_2KeyTyped
        if(med2_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med2_2KeyTyped

    private void med7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med7_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med7_2ActionPerformed

    private void med7_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med7_2KeyTyped
        if(med7_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med7_2KeyTyped

    private void med2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med2_3ActionPerformed

    private void med2_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med2_3KeyTyped
       if(med2_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med2_3KeyTyped

    private void med7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med7_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med7_3ActionPerformed

    private void med7_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med7_3KeyTyped
       if(med7_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med7_3KeyTyped

    private void med3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med3_1ActionPerformed

    private void med3_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med3_1KeyTyped
        if(med3_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med3_1KeyTyped

    private void med7_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med7_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med7_4ActionPerformed

    private void med7_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med7_4KeyTyped
        if(med7_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med7_4KeyTyped

    private void med2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med2_1ActionPerformed

    private void med2_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med2_1KeyTyped
        if(med2_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med2_1KeyTyped

    private void med7_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med7_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med7_5ActionPerformed

    private void med7_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med7_5KeyTyped
        if(med7_5.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med7_5KeyTyped

    private void med3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med3_2ActionPerformed

    private void med3_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med3_2KeyTyped
       if(med3_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med3_2KeyTyped

    private void med7_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med7_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med7_6ActionPerformed

    private void med7_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med7_6KeyTyped
        if(med7_6.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med7_6KeyTyped

    private void med3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med3_3ActionPerformed

    private void med3_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med3_3KeyTyped
        if(med3_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med3_3KeyTyped

    private void med3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med3_4ActionPerformed

    private void med3_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med3_4KeyTyped
        if(med3_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med3_4KeyTyped

    private void med3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med3_5ActionPerformed

    private void med3_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med3_5KeyTyped
        if(med3_5.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med3_5KeyTyped

    private void med4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med4_1ActionPerformed

    private void med4_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med4_1KeyTyped
        if(med4_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med4_1KeyTyped

    private void med4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med4_2ActionPerformed

    private void med4_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med4_2KeyTyped
        if(med4_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_med4_2KeyTyped

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        new FormInput().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void Btn_ulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ulangiActionPerformed
        cm.reset();
        
    }//GEN-LAST:event_Btn_ulangiActionPerformed

    private void btn_bantuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bantuMouseClicked
       cm.Bantuan(tbl_medium.getSelectedRow());
        
    }//GEN-LAST:event_btn_bantuMouseClicked

    private void btn_bantuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bantuActionPerformed
        
    }//GEN-LAST:event_btn_bantuActionPerformed

    private void btn_kumpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kumpulActionPerformed
        cm.check_jawab();
    }//GEN-LAST:event_btn_kumpulActionPerformed

    private void soalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_soalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level_Medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level_Medium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ulangi;
    private javax.swing.JButton btn_bantu;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_kumpul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField med1_1;
    private javax.swing.JTextField med1_10;
    private javax.swing.JTextField med1_2;
    private javax.swing.JTextField med1_3;
    private javax.swing.JTextField med1_4;
    private javax.swing.JTextField med1_5;
    private javax.swing.JTextField med1_6;
    private javax.swing.JTextField med1_7;
    private javax.swing.JTextField med1_8;
    private javax.swing.JTextField med1_9;
    private javax.swing.JTextField med2_1;
    private javax.swing.JTextField med2_2;
    private javax.swing.JTextField med2_3;
    private javax.swing.JTextField med3_1;
    private javax.swing.JTextField med3_2;
    private javax.swing.JTextField med3_3;
    private javax.swing.JTextField med3_4;
    private javax.swing.JTextField med3_5;
    private javax.swing.JTextField med4_1;
    private javax.swing.JTextField med4_2;
    private javax.swing.JTextField med4_3;
    private javax.swing.JTextField med4_4;
    private javax.swing.JTextField med5_1;
    private javax.swing.JTextField med5_2;
    private javax.swing.JTextField med5_3;
    private javax.swing.JTextField med5_4;
    private javax.swing.JTextField med6_1;
    private javax.swing.JTextField med6_2;
    private javax.swing.JTextField med6_3;
    private javax.swing.JTextField med6_4;
    private javax.swing.JTextField med6_5;
    private javax.swing.JTextField med7_1;
    private javax.swing.JTextField med7_2;
    private javax.swing.JTextField med7_3;
    private javax.swing.JTextField med7_4;
    private javax.swing.JTextField med7_5;
    private javax.swing.JTextField med7_6;
    private javax.swing.JLabel soal;
    private javax.swing.JTable tbl_medium;
    // End of variables declaration//GEN-END:variables
}
