/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Koneksi.KoneksiDB;
import Controller.ControllerTTS;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Level_Easy extends javax.swing.JFrame {

    ControllerTTS cb;
    Connection connection;
    /**
     * Creates new form Level_Easy
     */
  
    
    public Level_Easy() {
        initComponents();
       
        cb = new ControllerTTS(this);
        cb.isiTable();
        Tbl_Soal.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,11));
        Tbl_Soal.getTableHeader().setOpaque(false);
        Tbl_Soal.getTableHeader().setBackground(new Color(112, 112, 112));
        Tbl_Soal.getTableHeader().setForeground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_bantu = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        Btn_ulangi = new javax.swing.JButton();
        btn_kumpul = new javax.swing.JButton();
        TTS_Kesehatan = new javax.swing.JLabel();
        Level_Easy = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Soal = new javax.swing.JTable();
        No1 = new javax.swing.JLabel();
        No2 = new javax.swing.JLabel();
        No3 = new javax.swing.JLabel();
        jwb1_1 = new javax.swing.JTextField();
        jwb1_2 = new javax.swing.JTextField();
        jwb1_3 = new javax.swing.JTextField();
        jwb1_4 = new javax.swing.JTextField();
        jwb1_5 = new javax.swing.JTextField();
        jwb1_6 = new javax.swing.JTextField();
        jwb2_1 = new javax.swing.JTextField();
        jwb2_2 = new javax.swing.JTextField();
        jwb2_4 = new javax.swing.JTextField();
        jwb3_1 = new javax.swing.JTextField();
        jwb3_3 = new javax.swing.JTextField();
        jwb3_4 = new javax.swing.JTextField();
        jwb3_5 = new javax.swing.JTextField();
        jwb3_6 = new javax.swing.JTextField();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_bantu.setBackground(new java.awt.Color(102, 102, 102));
        btn_bantu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_bantu.setForeground(new java.awt.Color(255, 255, 255));
        btn_bantu.setText("Assist ");
        btn_bantu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bantuMouseClicked(evt);
            }
        });
        btn_bantu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bantuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bantu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 70, -1));

        btn_kembali.setBackground(new java.awt.Color(51, 51, 51));
        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("Back");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, 24));

        Btn_ulangi.setBackground(new java.awt.Color(102, 102, 102));
        Btn_ulangi.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Btn_ulangi.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ulangi.setText("Retry");
        Btn_ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ulangiActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_ulangi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 70, -1));

        btn_kumpul.setBackground(new java.awt.Color(102, 102, 102));
        btn_kumpul.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_kumpul.setForeground(new java.awt.Color(255, 255, 255));
        btn_kumpul.setText("Submit");
        btn_kumpul.setMaximumSize(new java.awt.Dimension(73, 21));
        btn_kumpul.setMinimumSize(new java.awt.Dimension(73, 21));
        btn_kumpul.setPreferredSize(new java.awt.Dimension(73, 21));
        btn_kumpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kumpulActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kumpul, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 70, 30));

        TTS_Kesehatan.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        TTS_Kesehatan.setForeground(new java.awt.Color(204, 255, 255));
        TTS_Kesehatan.setText("TTS Kesehatan");
        jPanel1.add(TTS_Kesehatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 11, -1, -1));

        Level_Easy.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        Level_Easy.setForeground(new java.awt.Color(102, 255, 153));
        Level_Easy.setText("Level Easy");
        jPanel1.add(Level_Easy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        Tbl_Soal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Soal.setSelectionBackground(new java.awt.Color(204, 204, 204));
        Tbl_Soal.getTableHeader().setReorderingAllowed(false);
        Tbl_Soal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_SoalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Soal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 300, 80));

        No1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        No1.setText("1.");
        jPanel1.add(No1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 158, 20, 20));

        No2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        No2.setText("2.");
        jPanel1.add(No2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 104, -1, -1));

        No3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        No3.setText("3.");
        jPanel1.add(No3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 134, -1, -1));

        jwb1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jwb1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jwb1_1ActionPerformed(evt);
            }
        });
        jwb1_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb1_1KeyTyped(evt);
            }
        });
        jPanel1.add(jwb1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 38, 30));

        jwb1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jwb1_2ActionPerformed(evt);
            }
        });
        jwb1_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb1_2KeyTyped(evt);
            }
        });
        jPanel1.add(jwb1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 38, 30));

        jwb1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb1_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb1_3KeyTyped(evt);
            }
        });
        jPanel1.add(jwb1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 38, 30));

        jwb1_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb1_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb1_4KeyTyped(evt);
            }
        });
        jPanel1.add(jwb1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 38, 30));

        jwb1_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb1_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb1_5KeyTyped(evt);
            }
        });
        jPanel1.add(jwb1_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 38, 30));

        jwb1_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb1_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb1_6KeyTyped(evt);
            }
        });
        jPanel1.add(jwb1_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 38, 30));

        jwb2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb2_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb2_1KeyTyped(evt);
            }
        });
        jPanel1.add(jwb2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 38, 30));

        jwb2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb2_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb2_2KeyTyped(evt);
            }
        });
        jPanel1.add(jwb2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 38, 30));

        jwb2_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb2_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb2_4KeyTyped(evt);
            }
        });
        jPanel1.add(jwb2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 38, 30));

        jwb3_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb3_1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jwb3_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb3_1KeyTyped(evt);
            }
        });
        jPanel1.add(jwb3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 38, 30));

        jwb3_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb3_3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jwb3_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb3_3KeyTyped(evt);
            }
        });
        jPanel1.add(jwb3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 38, 30));

        jwb3_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb3_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jwb3_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb3_4KeyTyped(evt);
            }
        });
        jPanel1.add(jwb3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 38, 30));

        jwb3_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb3_5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jwb3_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb3_5KeyTyped(evt);
            }
        });
        jPanel1.add(jwb3_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 38, 30));

        jwb3_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jwb3_6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jwb3_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jwb3_6KeyTyped(evt);
            }
        });
        jPanel1.add(jwb3_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 38, 30));

        Wallpaper.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\TTSku\\wallpaperflare.com_wallpaper.jpg")); // NOI18N
        Wallpaper.setText("jLabel3");
        jPanel1.add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tbl_SoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_SoalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tbl_SoalMouseClicked

    private void btn_kumpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kumpulActionPerformed
        cb.check_jawab();
    }//GEN-LAST:event_btn_kumpulActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        new FormInput().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_bantuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bantuMouseClicked
        // TODO add your handling code here:
        cb.Bantuan(Tbl_Soal.getSelectedRow());
    }//GEN-LAST:event_btn_bantuMouseClicked

    private void Btn_ulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ulangiActionPerformed
        // TODO add your handling code here:
        cb.reset();
    }//GEN-LAST:event_Btn_ulangiActionPerformed

    private void jwb1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jwb1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jwb1_1ActionPerformed

    private void btn_bantuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bantuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bantuActionPerformed

    private void jwb1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jwb1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jwb1_2ActionPerformed

    private void jwb1_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb1_1KeyTyped
        if(jwb1_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb1_1KeyTyped

    private void jwb1_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb1_2KeyTyped
        if(jwb1_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb1_2KeyTyped

    private void jwb1_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb1_3KeyTyped
        if(jwb1_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb1_3KeyTyped

    private void jwb1_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb1_4KeyTyped
        if(jwb1_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb1_4KeyTyped

    private void jwb1_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb1_5KeyTyped
       if(jwb1_5.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb1_5KeyTyped

    private void jwb1_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb1_6KeyTyped
       if(jwb1_6.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb1_6KeyTyped

    private void jwb3_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb3_1KeyTyped
       if(jwb3_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb3_1KeyTyped

    private void jwb3_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb3_3KeyTyped
       if(jwb3_3.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb3_3KeyTyped

    private void jwb3_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb3_4KeyTyped
        if(jwb3_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb3_4KeyTyped

    private void jwb3_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb3_5KeyTyped
        if(jwb3_5.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb3_5KeyTyped

    private void jwb3_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb3_6KeyTyped
        if(jwb3_6.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb3_6KeyTyped

    private void jwb2_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb2_1KeyTyped
        if(jwb2_1.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb2_1KeyTyped

    private void jwb2_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb2_2KeyTyped
        if(jwb2_2.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb2_2KeyTyped

    private void jwb2_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jwb2_4KeyTyped
        if(jwb2_4.getText().length() == 1)
        evt.consume();
    }//GEN-LAST:event_jwb2_4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level_Easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level_Easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level_Easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level_Easy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level_Easy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ulangi;
    private javax.swing.JLabel Level_Easy;
    private javax.swing.JLabel No1;
    private javax.swing.JLabel No2;
    private javax.swing.JLabel No3;
    private javax.swing.JLabel TTS_Kesehatan;
    private javax.swing.JTable Tbl_Soal;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton btn_bantu;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_kumpul;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jwb1_1;
    private javax.swing.JTextField jwb1_2;
    private javax.swing.JTextField jwb1_3;
    private javax.swing.JTextField jwb1_4;
    private javax.swing.JTextField jwb1_5;
    private javax.swing.JTextField jwb1_6;
    private javax.swing.JTextField jwb2_1;
    private javax.swing.JTextField jwb2_2;
    private javax.swing.JTextField jwb2_4;
    private javax.swing.JTextField jwb3_1;
    private javax.swing.JTextField jwb3_3;
    private javax.swing.JTextField jwb3_4;
    private javax.swing.JTextField jwb3_5;
    private javax.swing.JTextField jwb3_6;
    // End of variables declaration//GEN-END:variables

    public JTable getTbl_Soal() {
        return Tbl_Soal;
    }

    
    public void setTbl_Soal(JTable Tbl_Soal) {
        this.Tbl_Soal = Tbl_Soal;
    }

    public JButton getBtn_bantu() {
        return btn_bantu;
    }

    public void setBtn_bantu(JButton btn_bantu) {
        this.btn_bantu = btn_bantu;
    }

    public JButton getBtn_kembali() {
        return btn_kembali;
    }

    public void setBtn_kembali(JButton btn_kembali) {
        this.btn_kembali = btn_kembali;
    }

    public JButton getBtn_kumpul() {
        return btn_kumpul;
    }

    public void setBtn_kumpul(JButton btn_kumpul) {
        this.btn_kumpul = btn_kumpul;
    }

    public JTextField getJwb1_1() {
        return jwb1_1;
    }

    public void setJwb1_1(JTextField jwb1_1) {
        this.jwb1_1 = jwb1_1;
    }

    public JTextField getJwb1_2() {
        return jwb1_2;
    }

    public void setJwb1_2(JTextField jwb1_2) {
        this.jwb1_2 = jwb1_2;
    }

    public JTextField getJwb1_3() {
        return jwb1_3;
    }

    public void setJwb1_3(JTextField jwb1_3) {
        this.jwb1_3 = jwb1_3;
    }

    public JTextField getJwb1_4() {
        return jwb1_4;
    }

    public void setJwb1_4(JTextField jwb1_4) {
        this.jwb1_4 = jwb1_4;
    }

    public JTextField getJwb1_5() {
        return jwb1_5;
    }

    public void setJwb1_5(JTextField jwb1_5) {
        this.jwb1_5 = jwb1_5;
    }

    public JTextField getJwb1_6() {
        return jwb1_6;
    }

    public void setJwb1_6(JTextField jwb1_6) {
        this.jwb1_6 = jwb1_6;
    }
    
     public JTextField getJwb2_1() {
        return jwb2_1;
    }

    public void setJwb2_1(JTextField jwb2_1) {
        this.jwb2_1 = jwb2_1;
    }

    public JTextField getJwb2_2() {
        return jwb2_2;
    }

    public void setJwb2_2(JTextField jwb2_2) {
        this.jwb2_2 = jwb2_2;
    }
    
    public JTextField getJwb2_4() {
        return jwb2_4;
    }

    public void setJwb2_4(JTextField jwb2_4) {
        this.jwb2_4 = jwb2_4;
    }

    public JTextField getJwb3_1() {
        return jwb3_1;
    }

    public void setJwb3_1(JTextField jwb3_1) {
        this.jwb3_1 = jwb3_1;
    }

    public JTextField getJwb3_3() {
        return jwb3_3;
    }

    public void setJwb3_3(JTextField jwb3_3) {
        this.jwb3_3 = jwb3_3;
    }

    public JTextField getJwb3_4() {
        return jwb3_4;
    }

    public void setJwb3_4(JTextField jwb3_4) {
        this.jwb3_4 = jwb3_4;
    }

    public JTextField getJwb3_5() {
        return jwb3_5;
    }

    public void setJwb3_5(JTextField jwb3_5) {
        this.jwb3_5 = jwb3_5;
    }

    public JTextField getJwb3_6() {
        return jwb3_6;
    }

    public void setJwb3_6(JTextField jwb3_6) {
        this.jwb3_6 = jwb3_6;
    }

   
    
    

   
    

}
